version: '3.8'

services:
  ollama-embedding:
    image: ollama/ollama:latest
    container_name: zest-embedding-ollama
    ports:
      - "11435:11434"  # Map to non-popular port 11435
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:
    driver: local